
#Discovery servuce configuration
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

##Graph DB configuration
spring.neo4j.uri= bolt://localhost:7687
spring.neo4j.authentication.password=password
spring.neo4j.authentication.username=neo4j
